import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPORT = Path("conductor/govt_archive_registered_sources_report.json")
HEALTH = Path("conductor/archive_source_health.json")
PUBLICATION = Path("conductor/archive_publication_status.json")
CORPUS = Path("dist/corpus_manifest.json")
OUTPUT = Path("conductor/archive_health_summary.md")


def _load(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _bullet_map(values: dict[str, Any]) -> list[str]:
    return [f"- `{key}`: {value}" for key, value in sorted(values.items())]


def _table_rows(values: dict[str, Any]) -> list[str]:
    rows = ["| Key | Value |", "| --- | ---: |"]
    rows.extend(f"| `{key}` | {value} |" for key, value in sorted(values.items()))
    return rows


def _source_health_rows(sources: list[dict[str, Any]]) -> list[str]:
    rows = ["| Source | Status | Observed | Archived | Error |", "| --- | --- | ---: | ---: | --- |"]
    for source in sources:
        rows.append(
            "| {source_id} | {status} | {observed} | {archived} | {error} |".format(
                source_id=str(source.get("source_id") or ""),
                status=str(source.get("status") or ""),
                observed=source.get("observed_count") or 0,
                archived=source.get("archived_count") or 0,
                error=str(source.get("error") or "").replace("|", "\\|"),
            )
        )
    return rows


def _date_range_rows(values: dict[str, Any]) -> list[str]:
    rows = ["| Source | Earliest original timestamp | Latest original timestamp |", "| --- | --- | --- |"]
    for source, item in sorted(values.items()):
        rows.append(
            "| {source} | {min_date} | {max_date} |".format(
                source=source,
                min_date=item.get("min_original_created_at") or "",
                max_date=item.get("max_original_created_at") or "",
            )
        )
    return rows


def main() -> None:
    report = _load(REPORT)
    health = _load(HEALTH)
    publication = _load(PUBLICATION)
    corpus = _load(CORPUS)
    report_summary = report.get("summary") or {}
    corpus_counts = corpus.get("source_counts") or {}
    artifact = publication.get("artifact") or {}
    hf = publication.get("hugging_face") or {}
    zenodo = publication.get("zenodo") or {}

    lines = [
        "# Archive Health and Publication QA",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Latest registered-source run",
        "",
    ]
    if report_summary:
        lines.extend(_bullet_map(report_summary.get("status_counts") or {}))
        lines.append("")
        lines.append(f"Selected sources: {report_summary.get('selected_sources', 0)}")
        lines.append("")
        lines.extend(_table_rows(report_summary.get("platform_counts") or {}))
    else:
        lines.append("No registered-source report was available.")

    lines.extend([
        "",
        "## Source health snapshot",
        "",
        f"Generated by health check: {health.get('generated_at', '')}",
        "",
    ])
    if health.get("archived_counts"):
        lines.extend(_table_rows(health.get("archived_counts") or {}))
        lines.append("")
    if health.get("sources"):
        lines.extend(_source_health_rows(health.get("sources") or []))
    else:
        lines.append("No source health entries were available.")

    lines.extend([
        "",
        "## Corpus manifest",
        "",
        f"Canonical name: `{corpus.get('canonical_name', '')}`",
        f"Title: {corpus.get('title', '')}",
        f"Normalized records: {corpus.get('normalized_record_count', 0)}",
        f"Raw files: {corpus.get('raw_file_count', 0)}",
        "",
    ])
    if corpus_counts:
        lines.extend(_table_rows(corpus_counts))
        lines.append("")
    if corpus.get("source_date_ranges"):
        lines.extend(_date_range_rows(corpus.get("source_date_ranges") or {}))

    lines.extend([
        "",
        "## Publication status",
        "",
        f"Mode: `{publication.get('mode', '')}`",
        f"Release version: `{publication.get('release_version', '')}`",
        f"Bundle SHA-256: `{artifact.get('sha256', '')}`",
        f"Bundle file count: {artifact.get('file_count', 0)}",
        f"Bundle normalized records: {artifact.get('normalized_record_count', 0)}",
        f"Hugging Face: `{hf.get('status', '')}` -> `{hf.get('target', '')}`",
        f"Zenodo: `{zenodo.get('status', '')}` -> `{zenodo.get('target', '')}`",
        "",
        "## Completeness notes",
        "",
        "- RSS and Atom records are captured to the historical depth exposed by the feed endpoint at capture time; feeds that only expose recent entries cannot be fully backfilled without another source.",
        "- Bluesky records are captured through the public author-feed path and push/fallback inputs; historical depth depends on configured pagination limits and previously persisted captures.",
        "- Website page captures preserve the bounded public page response and extraction metadata, not a full crawl of every linked page.",
        "- Manual seed platforms, including Threads, Facebook, Instagram, LinkedIn, and X, remain provenance-dependent and should not be treated as complete until seed files or approved APIs are present.",
    ])

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
